// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppEigenH5.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// read_data_attr_h5_exp
Rcpp::CharacterVector read_data_attr_h5_exp(const StringVector h5filename, const StringVector h5_groupname, const StringVector h5_dataname, const StringVector h5_attr_name);
RcppExport SEXP RcppEigenH5_read_data_attr_h5_exp(SEXP h5filenameSEXP, SEXP h5_groupnameSEXP, SEXP h5_datanameSEXP, SEXP h5_attr_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector >::type h5filename(h5filenameSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type h5_groupname(h5_groupnameSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type h5_dataname(h5_datanameSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type h5_attr_name(h5_attr_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(read_data_attr_h5_exp(h5filename, h5_groupname, h5_dataname, h5_attr_name));
    return rcpp_result_gen;
END_RCPP
}
// read_group_attr_h5_exp
Rcpp::CharacterVector read_group_attr_h5_exp(const std::string h5file, const std::string groupname, const std::string attr_name);
RcppExport SEXP RcppEigenH5_read_group_attr_h5_exp(SEXP h5fileSEXP, SEXP groupnameSEXP, SEXP attr_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type h5file(h5fileSEXP);
    Rcpp::traits::input_parameter< const std::string >::type groupname(groupnameSEXP);
    Rcpp::traits::input_parameter< const std::string >::type attr_name(attr_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(read_group_attr_h5_exp(h5file, groupname, attr_name));
    return rcpp_result_gen;
END_RCPP
}
// read_2d_h5_exp
Eigen::MatrixXd read_2d_h5_exp(const StringVector h5file, const StringVector groupname, const StringVector dataname, const IntegerVector offset, const IntegerVector chunksize);
RcppExport SEXP RcppEigenH5_read_2d_h5_exp(SEXP h5fileSEXP, SEXP groupnameSEXP, SEXP datanameSEXP, SEXP offsetSEXP, SEXP chunksizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector >::type h5file(h5fileSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type groupname(groupnameSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type dataname(datanameSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type chunksize(chunksizeSEXP);
    rcpp_result_gen = Rcpp::wrap(read_2d_h5_exp(h5file, groupname, dataname, offset, chunksize));
    return rcpp_result_gen;
END_RCPP
}
// read_1d_h5
Eigen::ArrayXd read_1d_h5(const StringVector h5file, const StringVector groupname, const StringVector dataname, const IntegerVector offset, const IntegerVector chunksize);
RcppExport SEXP RcppEigenH5_read_1d_h5(SEXP h5fileSEXP, SEXP groupnameSEXP, SEXP datanameSEXP, SEXP offsetSEXP, SEXP chunksizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector >::type h5file(h5fileSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type groupname(groupnameSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type dataname(datanameSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type chunksize(chunksizeSEXP);
    rcpp_result_gen = Rcpp::wrap(read_1d_h5(h5file, groupname, dataname, offset, chunksize));
    return rcpp_result_gen;
END_RCPP
}
// read_1i_h5
Eigen::ArrayXi read_1i_h5(const StringVector h5file, const StringVector groupname, const StringVector dataname, const IntegerVector offset, const IntegerVector chunksize);
RcppExport SEXP RcppEigenH5_read_1i_h5(SEXP h5fileSEXP, SEXP groupnameSEXP, SEXP datanameSEXP, SEXP offsetSEXP, SEXP chunksizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector >::type h5file(h5fileSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type groupname(groupnameSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type dataname(datanameSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type chunksize(chunksizeSEXP);
    rcpp_result_gen = Rcpp::wrap(read_1i_h5(h5file, groupname, dataname, offset, chunksize));
    return rcpp_result_gen;
END_RCPP
}
// read_2d_mat_h5
Eigen::MatrixXd read_2d_mat_h5(const StringVector h5file, const StringVector groupname, const StringVector dataname);
RcppExport SEXP RcppEigenH5_read_2d_mat_h5(SEXP h5fileSEXP, SEXP groupnameSEXP, SEXP datanameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector >::type h5file(h5fileSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type groupname(groupnameSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type dataname(datanameSEXP);
    rcpp_result_gen = Rcpp::wrap(read_2d_mat_h5(h5file, groupname, dataname));
    return rcpp_result_gen;
END_RCPP
}
// read_2d_index_h5
Eigen::MatrixXd read_2d_index_h5(const StringVector h5file, const StringVector groupname, const StringVector dataname, const IntegerVector indvec);
RcppExport SEXP RcppEigenH5_read_2d_index_h5(SEXP h5fileSEXP, SEXP groupnameSEXP, SEXP datanameSEXP, SEXP indvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector >::type h5file(h5fileSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type groupname(groupnameSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type dataname(datanameSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type indvec(indvecSEXP);
    rcpp_result_gen = Rcpp::wrap(read_2d_index_h5(h5file, groupname, dataname, indvec));
    return rcpp_result_gen;
END_RCPP
}
// read_1d_index_h5
Eigen::ArrayXd read_1d_index_h5(const StringVector h5file, const StringVector groupname, const StringVector dataname, const IntegerVector indvec);
RcppExport SEXP RcppEigenH5_read_1d_index_h5(SEXP h5fileSEXP, SEXP groupnameSEXP, SEXP datanameSEXP, SEXP indvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector >::type h5file(h5fileSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type groupname(groupnameSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type dataname(datanameSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type indvec(indvecSEXP);
    rcpp_result_gen = Rcpp::wrap(read_1d_index_h5(h5file, groupname, dataname, indvec));
    return rcpp_result_gen;
END_RCPP
}
// h5_rownum
Rcpp::IntegerVector h5_rownum(const std::string h5file, const std::string groupname, const std::string dataname);
RcppExport SEXP RcppEigenH5_h5_rownum(SEXP h5fileSEXP, SEXP groupnameSEXP, SEXP datanameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type h5file(h5fileSEXP);
    Rcpp::traits::input_parameter< const std::string >::type groupname(groupnameSEXP);
    Rcpp::traits::input_parameter< const std::string >::type dataname(datanameSEXP);
    rcpp_result_gen = Rcpp::wrap(h5_rownum(h5file, groupname, dataname));
    return rcpp_result_gen;
END_RCPP
}
// h5_colnum
Rcpp::IntegerVector h5_colnum(const std::string h5file, const std::string groupname, const std::string dataname);
RcppExport SEXP RcppEigenH5_h5_colnum(SEXP h5fileSEXP, SEXP groupnameSEXP, SEXP datanameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type h5file(h5fileSEXP);
    Rcpp::traits::input_parameter< const std::string >::type groupname(groupnameSEXP);
    Rcpp::traits::input_parameter< const std::string >::type dataname(datanameSEXP);
    rcpp_result_gen = Rcpp::wrap(h5_colnum(h5file, groupname, dataname));
    return rcpp_result_gen;
END_RCPP
}
// h5ls_grp_exp
std::vector<std::string> h5ls_grp_exp(std::string h5file, std::string base_group);
RcppExport SEXP RcppEigenH5_h5ls_grp_exp(SEXP h5fileSEXP, SEXP base_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type h5file(h5fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type base_group(base_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(h5ls_grp_exp(h5file, base_group));
    return rcpp_result_gen;
END_RCPP
}
// h5ls_attr_exp
std::vector<std::string> h5ls_attr_exp(std::string h5file, std::string base_group);
RcppExport SEXP RcppEigenH5_h5ls_attr_exp(SEXP h5fileSEXP, SEXP base_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type h5file(h5fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type base_group(base_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(h5ls_attr_exp(h5file, base_group));
    return rcpp_result_gen;
END_RCPP
}
