# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_data_attr_h5 <- function(h5filename, h5_groupname, h5_dataname, h5_attr_name) {
    .Call('RcppEigenH5_read_data_attr_h5_exp', PACKAGE = 'RcppEigenH5', h5filename, h5_groupname, h5_dataname, h5_attr_name)
}

read_group_attr_h5 <- function(h5file, groupname, attr_name) {
    .Call('RcppEigenH5_read_group_attr_h5_exp', PACKAGE = 'RcppEigenH5', h5file, groupname, attr_name)
}

read_2d_h5 <- function(h5file, groupname, dataname, offset, chunksize) {
    .Call('RcppEigenH5_read_2d_h5_exp', PACKAGE = 'RcppEigenH5', h5file, groupname, dataname, offset, chunksize)
}

read_1d_h5 <- function(h5file, groupname, dataname, offset, chunksize) {
    .Call('RcppEigenH5_read_1d_h5', PACKAGE = 'RcppEigenH5', h5file, groupname, dataname, offset, chunksize)
}

read_1i_h5 <- function(h5file, groupname, dataname, offset, chunksize) {
    .Call('RcppEigenH5_read_1i_h5', PACKAGE = 'RcppEigenH5', h5file, groupname, dataname, offset, chunksize)
}

read_2d_mat_h5 <- function(h5file, groupname, dataname) {
    .Call('RcppEigenH5_read_2d_mat_h5', PACKAGE = 'RcppEigenH5', h5file, groupname, dataname)
}

read_2d_index_h5 <- function(h5file, groupname, dataname, indvec) {
    .Call('RcppEigenH5_read_2d_index_h5', PACKAGE = 'RcppEigenH5', h5file, groupname, dataname, indvec)
}

read_1d_index_h5 <- function(h5file, groupname, dataname, indvec) {
    .Call('RcppEigenH5_read_1d_index_h5', PACKAGE = 'RcppEigenH5', h5file, groupname, dataname, indvec)
}

get_rownum_h5 <- function(h5file, groupname, dataname) {
    .Call('RcppEigenH5_h5_rownum', PACKAGE = 'RcppEigenH5', h5file, groupname, dataname)
}

get_colnum_h5 <- function(h5file, groupname, dataname) {
    .Call('RcppEigenH5_h5_colnum', PACKAGE = 'RcppEigenH5', h5file, groupname, dataname)
}

list_groups_h5 <- function(h5file, base_group = "/") {
    .Call('RcppEigenH5_h5ls_grp_exp', PACKAGE = 'RcppEigenH5', h5file, base_group)
}

list_attrs_h5 <- function(h5file, base_group = "/") {
    .Call('RcppEigenH5_h5ls_attr_exp', PACKAGE = 'RcppEigenH5', h5file, base_group)
}

